apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: rimorin@live.com
    privateKeySecretRef:
      name: letsencrypt-issuer-staging
    solvers:
      - http01:
          ingress:
            class: nginx
